spring:
  application:
    name: hello
server:
  port: 8011
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
logging:
  level:
    root: debug
#  path: D:/logs
  file: D:/logs/hello.log
